### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by cognitom** [riot/examples#1]
_This issue is originally opened at https://github.com/riot/riot.github.io/issues/7 and we decided to create this `examples` repo. I'd like to continue the discussion here._
### Playground

We can show it in `<iframe>` with our live editor.
- [ ] The simplest example and also a nice tutorial on Plunker.
### Basics

Well tested examples for the beginners. If compatible with Plunker, we can add the "edit on Plunker" button.
- [x] [Todo App](https://github.com/riot/examples/tree/master/todo-app)
- [x] [Todo App (pre-compiled)](https://github.com/riot/examples/tree/master/todo-app-precompiled)
- [x] [Timer](https://github.com/riot/examples/tree/master/timer)
- [x] [Router - Page switcher](https://github.com/riot/examples/tree/master/router-page-switcher)
- [x] [Mixins](https://github.com/riot/examples/tree/master/mixins) by @gregorypratt 
- [x] [Observables](https://github.com/riot/examples/tree/master/observables) by @gregorypratt 
### Bug Reporter
- [x] [Riot Bug Reporter](https://github.com/riot/examples/tree/master/bug-reporter)
### More

Relatively not tested well, but good resources for the people who want to learn more.
- [x] Webpack setups
- [ ] gulp setups
- [ ] Browserify setups
- [x] How to write in ES6
- [ ] Isomorphic App
- [x] Router - pushState
- [ ] Hackathon starter - cf. [Angular's one](https://github.com/johnlindquist/ng-hackathon-starter)
- [x] [Plunker opener](https://github.com/riot/examples/tree/master/plunker)
- [x] [Live editor](https://github.com/riot/examples/tree/master/live-editor)
- [ ] Performance tips

**Comment by gregorypratt** [comment]
- How to use Mixins
- How to use ES6 modules (can you?)

**Comment by aMarCruz** [comment]
:+1: 
performance tips

**Comment by cognitom** [comment]
@gregorypratt thanks! Pls send it as a PR ;)

Note: we can register [mixin without using globals](http://plnkr.co/edit/TkOQ1p?p=preview).

```javascript
riot.mixin('MessageMixin', {...})
```

**Comment by gregorypratt** [comment]
Cool. Will do. And update to not use global. Which I was wondering about too!

**Comment by restlessmedia** [comment]
riotjs + commonjs + browserify?

**Comment by karolyi** [comment]
unit (tag) testing?

**Comment by GianlucaGuarini** [comment]
@karolyi isn't [this enough](https://github.com/riot/examples/blob/gh-pages/timer/test/specs.js)?

**Comment by karolyi** [comment]
@GianlucaGuarini I'm currently looking at riot's own unit test but it seems a bit voodoo for me.

my concern is that I'd like to have separated unit tests for each of my tags, but the tags sometimes nest another tags, thus I can't really separate them in a good way.

any hints on that would be helpful.

**Comment by GianlucaGuarini** [comment]
Indeed I have linked to a test file that was testing only single tag `<timer>`

**Comment by karolyi** [comment]
@GianlucaGuarini after looking at riot's own unit tests, do I assume it right that it doesn't handle nested tags? nor is there a way for that?

**Comment by GianlucaGuarini** [comment]
> do I assume it right that it doesn't handle nested tags? nor is there a way for that?

what do you mean? Can you make an example repo? A unit test depends a lot on how you build it there is no standard way to do it. In a unit test you can test nested tags as well depending on what you mount in your test markup

**Comment by karolyi** [comment]
I actually have one ongoing: https://github.com/karolyi/forum-django

you can clone it, and then `npm install`, `karma start` or `gulp webpack-dev-server` and navigate to `http://localhost:8081`

what you'll see here is that `index.tag` has a nested tag called `test-tag`, which gets mounted automatically. because of that, I can't separately test the functionality of `index.tag` in the future, as it would communicate with `test.tag` (and everything else that gets mounted there either as a sibling or as a 'deep-mount', meaning nested tags of nested tags). What I wanted to achieve is to have `test-tag` not mounted (despite having it loaded), so I could mock/emulate all the behavior of that tag.

I want to be able to span the tags individually _without_ automounting their nested tags, thus separating their tests. I looked for an option to stop the automounting of any nested tag, found no clue about it.

**Comment by GianlucaGuarini** [comment]
Have you also checked [karma riot](https://github.com/riot/karma-riot)? I think that if you need to test individually each nested tag you can use something like:
`karma.config.js`

``` js
// karma.conf.js
module.exports = function(config) {
  config.set({
    frameworks: ['mocha', 'riot'],
    plugins: [
      'karma-mocha',
      'karma-mocha-reporter',
      'karma-phantomjs-launcher',
      'karma-riot'
    ],
    files: [
      'path/to/your/tags/**/*.tag',
      'test/**/*.js'
    ],
    preprocessors: {
      'path/to/your/tags/**/*.tag': ['riot']
    },
    riotPreprocessor: {
       options: {
         type: 'babel'
       }
    },
    browsers: ['PhantomJS'],
    reporters: ['mocha']
  })
}
```

and in `test/my-tag.spec.js`:

``` js
describe('karma-riot specs', function() {
  it('mounts my-tag', function() {
    var html = document.createElement('my-tag')
    document.body.appendChild(html)
    riot.mount('my-tag')
    expect(document.querySelector('my-tag > h1').textContent).to.be('Hello!')
  })
})
```

**Comment by karolyi** [comment]
@GianlucaGuarini yes I checked it out, and I use it.

it seems that the only viable solution so far is to define a karma.conf for each tag and their test, by passing only the respective file and its test to karma. which is kinda overkill.

if you take a look at my aforementioned repo, you'll see that karma imports all the tags by the `files` specification, thus all the tags get imported and initialized/automounted.

this is especially the thing I would want to avoid.

other option would be to be able to dynamically deregister a HTML tag, formerly registered by riot itself. unfortunately, I couldn't find a way for that.

**Comment by GianlucaGuarini** [comment]
Ok so then you can simply use:

``` js
describe(function() {
   before(function(done) {
     riot.compile('path/to/your/tag/my-tag.tag', done)
   })
   // add your tests here
})
```

**Comment by karolyi** [comment]
A question: what do I need in order to have `riot.compile` in the browser? using `karma-riot` didn't work, tried including `node_modules/riot/lib/browser/compiler/compile.js` but it errored.

**Comment by karolyi** [comment]
Okay, I solved it! The following steps were necessary:
- Since I'm using babel to transpile the javascript source from es6 to es5, I needed to install `babel-standalone` and put `node_modules/babel-standalone/babel.js` to the files config
- babel is now exported to the test environment, but `riot+compile.js` looks for it with `window.babel`, whereas it is exported with `window.Babel`. See [here](https://github.com/riot/riot/blob/master/riot%2Bcompiler.js#L2594), please change this part
- managed to change your code so that the compiled code is inserted and the tag is compiled.

with these changes, I managed to separate the tests! which is a huge step forward.

the takeaway here is:
- `Babel` exporing itself in capitalized string caused some headache, _please change the mentioned line_
- in order to be able to separately tests all tags (nested ones), use [my latest boilerplate](https://github.com/karolyi/forum-django/tree/fb8c056963dd9ea6bf88567fcfbf7752176e3537)

would you please change that line so that `babel` would work? thx

**Comment by karolyi** [comment]
Hrm, let me take my former comment back.

Whereas the thing with `window.Babel` was right, after replacing the order of the inclusion, the nested element automounted again. ouch.

since karma is executing all tests in the same iframe (afaik there's no way to execute each test in a separate iframe) we can't really solve this problem.

@GianlucaGuarini, any opinions?

**Comment by karolyi** [comment]
Further investigating in riot.js, found out that there's no way do deregister an element registered with `riot.tag2`.

If I could have something like it, with which I could simply deregister an element after testing it, it wouldn't automount, and I could separate tests.

**Comment by karolyi** [comment]
I think because of that, I'll have to go back to React. [They have this problem solved by mocking nested elements.](https://nemisj.com/how-to-test-react-js-components/)

This is really unfortunate, as I liked riot the way it is, but it seems too immature for extended testing. Until a function which hinders nested elements from automounting (either with deregistering elements or by passing an option to `riot.mount` to not mount nested elements), unit testing with separation of concerns is impossible.

Keep pushing the pace guys, riotjs has the possibility to outgrow react, one day. I'll be keeping an eye on this project.

**Comment by yckart** [comment]
A bit unconstructive, but I hate Plunker!

**Comment by cognitom** [comment]
Now, thanks to all, we have a lot of examples. I'm closing this.

Then, it's a time to upgrade those to Riot 3: #39 😄
